require "logan.options"
require "logan.keymaps"
require "logan.plugins"
require "logan.colorscheme"
require "logan.gui"
require "logan.autocomplete"
require "logan.lsp"
require "logan.telescope"
require "logan.treesitter"
require "logan.alpha" --Dashboard on open
require "logan.autopairs"
require "logan.comment"
require "logan.gitsigns"
require "logan.nvim-tree"
require "logan.bufferline"
require "logan.toggleterm"
require "logan.indentline"
-- require "logan.transparent"
require "logan.harpoon"
require "logan.gitconflict"
require "logan.crates"
require "logan.twilight"
require "logan.zen"
require "logan.sessions"
require "logan.autosave"
