-- :help options
vim.opt.tabstop = 4
vim.opt.softtabstop = 4
vim.opt.shiftwidth = 4
vim.opt.number = true
vim.opt.expandtab = true
vim.opt.exrc = true
vim.opt.nu = true
vim.opt.hidden = true
vim.opt.errorbells = false
vim.opt.swapfile = false
vim.opt.backup = false
vim.opt.undodir = os.getenv("HOME") .."/.vim/undodir"
vim.opt.undofile = true
vim.opt.incsearch = true
vim.opt.scrolloff = 15
vim.opt.signcolumn = "yes"
vim.opt.colorcolumn = "100"
--vim.cmd "set colorcolumn=100"
vim.opt.termguicolors = true
vim.opt.cmdheight = 2
vim.opt.relativenumber = true
vim.opt.updatetime=50
vim.opt.shortmess:append "c"
vim.opt.mouse = "a"
--vim.cmd "set shortmess+=:c"
vim.opt.laststatus = 3
vim.opt.wrap = false
vim.opt.autoread = true -- still need to manually trigger with e using terminal
vim.opt.spell = true
