set tabstop=4 softtabstop=4
set shiftwidth=4
set expandtab
set exrc
set nu
set hidden
set noerrorbells
set noswapfile
set nobackup
set undodir=~/.nvim/undodir
set undofile
set incsearch
set scrolloff=15
set signcolumn=yes
set colorcolumn=100
set termguicolors
set cmdheight=2
set relativenumber
set updatetime=50
set shortmess+=c